# e2e-marqeta-simulator/Dockerfile.visa
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/visa.py ./
EXPOSE 8102
CMD ["uvicorn", "visa:app", "--host", "0.0.0.0", "--port", "8102"]
