# frontend/utils/html_report.py
"""HTML and JUnit report builders for test suite results."""


def build_html_report(suite_result: dict) -> str:
    """Generate a styled HTML test report from a suite result dict."""
    from jinja2 import Environment

    template_str = """<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>{{ suite_name }} - Test Report</title>
<style>
  body{font-family:Arial,sans-serif;margin:32px;color:#333}
  h1{color:#1f77b4}
  .badge{padding:4px 14px;border-radius:4px;font-weight:bold;color:#fff}
  .pass{background:#28a745}.fail{background:#dc3545}
  table{border-collapse:collapse;width:100%;margin-top:24px}
  th{background:#f5f5f5;padding:10px 8px;text-align:left;border-bottom:2px solid #ddd;font-size:.9em}
  td{padding:8px;border-bottom:1px solid #eee;font-size:.88em}
  tr.pass-row td:first-child{color:#28a745;font-weight:bold}
  tr.fail-row td:first-child{color:#dc3545;font-weight:bold}
  .meta{color:#666;font-size:.9em;margin:12px 0}
</style></head><body>
<h1>{{ suite_name }}</h1>
<p class="meta">
  Run: <b>{{ run_at }}</b> &nbsp;|&nbsp; {{ passed }}/{{ total }} passed
  &nbsp;|&nbsp; {{ duration_ms }} ms &nbsp;
  <span class="badge {{ 'pass' if passed == total else 'fail' }}">
    {{ 'ALL PASS' if passed == total else 'HAS FAILURES' }}
  </span>
</p>
<table>
<tr><th>Result</th><th>Scenario</th><th>Exp RC</th><th>Act RC</th>
    <th>Exp Decision</th><th>Act Decision</th><th>ms</th></tr>
{% for r in results %}
<tr class="{{ 'pass-row' if r.passed else 'fail-row' }}">
  <td>{{ '✅ PASS' if r.passed else '❌ FAIL' }}</td>
  <td>{{ r.name }}</td>
  <td>{{ r.expected_network_response_code }}</td>
  <td>{{ r.actual_network_response_code }}</td>
  <td>{{ r.expected_customer_decision }}</td>
  <td>{{ r.actual_customer_decision }}</td>
  <td>{{ r.duration_ms }}</td>
</tr>
{% endfor %}
</table>
<p style="color:#aaa;font-size:.8em;margin-top:32px">
  Generated by Marqeta E2E Simulator
</p>
</body></html>"""
    return Environment().from_string(template_str).render(**suite_result)


def build_junit_xml(suite_result: dict) -> str:
    """Generate JUnit XML from a suite result dict (for CI pipelines)."""
    results = suite_result.get("results", [])
    total = suite_result.get("total", len(results))
    failures = suite_result.get("failed", 0)
    duration_s = round((suite_result.get("duration_ms") or 0) / 1000, 3)
    suite_name = suite_result.get("suite_name", "Marqeta Suite")

    cases = []
    for r in results:
        name = r.get("name", r.get("scenario_id", "unknown"))
        t = round((r.get("duration_ms") or 0) / 1000, 3)
        case = f'    <testcase name="{_esc(name)}" classname="{_esc(suite_name)}" time="{t}">'
        if not r.get("passed"):
            exp_rc = r.get("expected_network_response_code", "?")
            act_rc = r.get("actual_network_response_code", "?")
            exp_d = r.get("expected_customer_decision", "?")
            act_d = r.get("actual_customer_decision", "?")
            msg = f"RC expected={exp_rc} actual={act_rc}; Decision expected={exp_d} actual={act_d}"
            case += (
                f'\n      <failure message="{_esc(msg)}">'
                f"{_esc(msg)}"
                f"</failure>\n    "
            )
        case += "</testcase>"
        cases.append(case)

    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<testsuites name="{_esc(suite_name)}" tests="{total}" '
        f'failures="{failures}" time="{duration_s}">\n'
        f'  <testsuite name="{_esc(suite_name)}" tests="{total}" '
        f'failures="{failures}" time="{duration_s}">\n'
        + "\n".join(cases)
        + "\n  </testsuite>\n</testsuites>"
    )


def _esc(s: str) -> str:
    """Minimal XML character escaping."""
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
